//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TiendaMVCDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto : IEnumerable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.ProductoAlmacen = new HashSet<ProductoAlmacen>();
            this.Etiqueta = new HashSet<Etiqueta>();
        }
    
        public int IdProducto { get; set; }
        [Required(ErrorMessage = "El Nombre del producto es obligatorio")]
        [DisplayName("Nombre del Producto")]
        public string Nombre { get; set; }
        [DisplayName("Fabricante")]
        [DataType(DataType.Text)]
        public string Fabricante { get; set; }
        [DisplayName("Precio Venta")]
        [DataType(DataType.Currency)]
        public decimal PvP { get; set; }
        [DisplayName("Precio Coste")]
        [DataType(DataType.Currency)]
        public decimal PvC { get; set; }
        [Range(1,4)]
        public int IdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoAlmacen> ProductoAlmacen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiqueta> Etiqueta { get; set; }

        public IEnumerator GetEnumerator()
        {
            throw new NotImplementedException();
        }
    }
}
